---
extends:
- plugin:@typescript-eslint/recommended
- react-app
- prettier
- prettier/@typescript-eslint
plugins:
- react
- "@typescript-eslint"
# - prettier
env:
  browser: true
  jasmine: true
  jest: true
rules:
#   prettier/prettier:
  # - error
  # - singleQuote: true
#   - semi: true
  semi:
  - 'error'
  - 'never'
settings:
  react:
    pragma: React
    version: detect
parser: "@typescript-eslint/parser"

