---
parser: '@typescript-eslint/parser'
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
plugins:
  - react
  - '@typescript-eslint'
env:
  browser: true
  jasmine: true
  jest: true
rules:
  '@typescript-eslint/explicit-function-return-type':
    - 'error'
    - allowTypedFunctionExpressions: true
settings:
  react:
    pragma: React
    version: detect
